$schema: "https://json-schema.org/draft/2020-12/schema"
description: global configuration
properties:
  manifest:
    type: string
  reference-genome:
    type: object
    properties:
      name:
        type: string
      fasta:
        type: string
    required:
      - name
      - fasta
    additionalProperties: no
required:
  - manifest
  - reference-genome
additionalProperties: no
